use anchor_lang::prelude::*;

declare_id!("D3tJsQ2Ad36CNK68H9P9porbsmQAyXz8WxxN3CfkDi91");

// Config: Platform takes 5%

const PLATFORM_FEE_PERCENTAGE: u64 = 5;

// Admin Treasury (Your wallet)

pub mod admin {
    use super::*;
    pub const TREASURY_KEY: Pubkey = pubkey!("H5DiQKbhnKM2GMtpc953QZJwVCEi5zDawkseH3zGMg86");
}

#[program]
pub mod solana_arweave_store {
    use super::*;

    // Arguments: 
    // - content_id: A random UUID generated by the frontend (e.g., "123-abc")
    // - arweave_hash: The link to the file
    // - title: Display name
    // - price: Cost in Lamports
    pub fn list_content(
        ctx: Context<ListContent>, 
        content_id: String, 
        arweave_hash: String, 
        title: String,
        price: u64
    ) -> Result<()> {
        let listing = &mut ctx.accounts.listing_pda;
        
        listing.authority = ctx.accounts.seller.key();
        listing.content_id = content_id;
        listing.arweave_hash = arweave_hash;
        listing.title = title;
        listing.price = price;
        listing.bump = ctx.bumps.listing_pda;
        
        msg!("Listed: {}", listing.title);
        Ok(())
    }
}

#[derive(Accounts)]
#[instruction(content_id: String, arweave_hash: String, title: String, price: u64)]
pub struct ListContent<'info> {
    #[account(mut)]
    pub seller: Signer<'info>,

    #[account(
        init,
        payer = seller,
        // SEED CHANGE: Use the UUID (content_id) as the seed, not the hash
        seeds = [b"listing", content_id.as_bytes()], 
        bump,
        // Space calculation (Adjust lengths as needed)
        // 8 (disc) + 32 (auth) + (4+36) (uuid) + (4+43) (hash) + (4+64) (title) + 8 (price) + 1 (bump)
        space = 8 + 32 + (4 + 36) + (4 + 43) + (4 + 64) + 8 + 1
    )]
    pub listing_pda: Account<'info, Listing>,

    pub system_program: Program<'info, System>,
}

#[account]
pub struct Listing {
    pub authority: Pubkey,
    pub content_id: String,  // The logical ID
    pub arweave_hash: String, // The storage pointer
    pub title: String,       // Fast lookup for UI
    pub price: u64,
    pub bump: u8,
}